import turtle

turtle.begin_fill()
turtle.color("red")
turtle.hideturtle()
turtle.speed(10)
turtle.pu()
turtle.goto(0, -200)
turtle.pd()
turtle.left(150)
turtle.forward(120)
turtle.circle(-50, 120)
turtle.setheading(0)
turtle.circle(-20, 90)
turtle.forward(30)
turtle.left(120)
turtle.circle(-50, 120)
turtle.forward(120)
turtle.end_fill()
turtle.done()